version: '3.8'

services:
  web:
    image: php:8.2-apache
    container_name: samjin_dev
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - PORT=80
    command: >
      sh -c "a2enmod rewrite &&
             apache2ctl -D FOREGROUND"
